# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://geo_projects:geo_projects@db:5432/geo_projects
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=geo_projects
      - POSTGRES_PASSWORD=geo_projects
      - POSTGRES_DB=geo_projects

  pytest:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest
    volumes:
      - .:/app

volumes:
  postgres_data:
